ALTER TYPE "EventType" ADD VALUE 'ENGINE_OVERREV';
ALTER TYPE "EventType" ADD VALUE 'WHEELIE_DETECTED';
ALTER TYPE "EventType" ADD VALUE 'STOPPIE_DETECTED';
ALTER TYPE "EventType" ADD VALUE 'SAFETY_SYSTEM_ACTIVE';
